trurl: add support for libcurl versions below 7.80.0
curl/trurl pull request #85
Opened 2023-04-05 17:56 UTC by baykovr

This patch allows compiling with versions of libcurl as low as 7.68.0 (the latest available to Ubuntu 20.04 LTS #67). 

This approach gets us building, with okay test coverage but it should be better. @bagder I'm not great at C but happy to learn and contribute, could you advise on how the implementation may be improved?

### Tests
The test coverage fails 2 of 49.
```
not ok 28 - ./trurl --url https://10.1/we/are.html --get "{host}"
#   Failed test './trurl --url https://10.1/we/are.html --get "{host}"'
#   at ./test.pl line 66.
#          got: '10.1'
#     expected: '10.0.0.1'
not ok 29 - ./trurl --url https://[fe80::0000:20c:29ff:fe9c:409b]:8080/we/are.html --get "{host}"
#   Failed test './trurl --url https://[fe80::0000:20c:29ff:fe9c:409b]:8080/we/are.html --get "{host}"'
#   at ./test.pl line 66.
#          got: '[fe80::0000:20c:29ff:fe9c:409b]'
#     expected: '[fe80::20c:29ff:fe9c:409b]'
```

### Warns
```
trurl.c: In function ‘get’:
trurl.c:51:25: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
   51 | #define PROGNAME        "trurl"
      |                         ^~~~~~~
trurl.c:387:31: note: in expansion of macro ‘PROGNAME’
  387 |               fprintf(stderr, PROGNAME ": %s (%s)\n", curl_url_strerror(rc),
      |                               ^~~~~~~~
trurl.c:387:44: note: format string is defined here
  387 |               fprintf(stderr, PROGNAME ": %s (%s)\n", curl_url_strerror(rc),
      |                                           ~^
      |                                            |
      |                                            char *
      |                                           %d
trurl.c:383:13: warning: case value ‘18’ not in enumerated type ‘CURLUcode’ {aka ‘enum <anonymous>’} [-Wswitch]
  383 |             case CURLUE_NO_ZONEID:
      |             ^~~~
cc   trurl.o  -lcurl -o trurl
```

2023-04-05 22:10 UTC, bagder requested changes
Thanks a lot for this. I had some minor comments on it...

2023-04-05 22:10 UTC, bagder commented on Makefile
> +	-D LIBCURL_VERNUM="$(shell curl-config --vernum)"
`LIBCURL_VERSION_NUM` is already provided in the public headers. No need for any magic shell tricks to get it!

2023-04-05 22:10 UTC, bagder commented on trurl.c
> +  fprintf(stderr, "URL error: %s\n", curl_easy_strerror(error))
curl_easy_strerror() cannot do the same job, they work on different number ranges

2023-04-05 22:10 UTC, bagder commented on trurl.c
> +#define CURLU_ALLOW_SPACE 0
This makes it build, but  `--accept-space` will not work. Shouldn't we then output some warning or something is that option is still used?

2023-04-06 03:39 UTC, baykovr commented on Makefile
> +	-D LIBCURL_VERNUM="$(shell curl-config --vernum)"
Fixed! Thanks for the tip.

2023-04-07 18:14 UTC, baykovr commented on trurl.c
> +#define CURLU_ALLOW_SPACE 0
In cases --accept-space is specified, and `CURLU_ALLOW_SPACE` is false we now emit a warning and disable the accept-space behavior (sample below). This results in test cases breaking, but I can fix them up as well (perhaps to detect the warning in the pl). 

Thoughts on the implementation?
```
./trurl  --accept-space --url "gopher://localhost/ with space"  -g '{path}'
trurl note: --accept-space is not supported in this version of libcurl
/ with space
```

2023-04-07 18:23 UTC, baykovr commented on trurl.c
> +  fprintf(stderr, "URL error: %s\n", curl_easy_strerror(error))
This one was very challenging, my goal was to at last emit the numeric error code to the user such that they may look it up, however I am not clever enough to solve this within the macro!

I tried the following
```C
#define curl_url_strerror(error) \
fprintf(stderr, "CURLUcode: %d\n", error)
```
 but this results in a segfault since we are not actually returning a `const char*`.

I then tried more clever tricks but hit `ISO C forbids braced-groups within expressions` which would harm portability ... and lastly worry that I will end up introducing a buffer overflow or some other terrible thing with other approaches.

I thus settled on a static error message, which I am unhappy with since we will eat the error code in such a case - it's safe and it works but it's not great. Thoughts?
```
./trurl ':<>https!!??illegal/https://foo.com'                               
trurl note: unsupported CURLUcode error [:<>https!!??illegal/https://foo.com]
trurl error: not enough input for a URL
trurl error: Try trurl -h for help
```

2023-04-07 18:29 UTC, baykovr commented
(Will rebase and fix conflicts once we agree on an approach - happy to revise this over and over until it's well done.)

2023-04-07 19:30 UTC, bagder commented on trurl.c
> +  "unsupported CURLUcode error"
I think it should rather be `fprintf(stderr, "URL error: %u\n", (int)error);`

2023-04-07 19:30 UTC, bagder commented on trurl.c
> +      op->accept_space = false;
No need to assign it to false when it already is false and will remain so.

2023-04-07 20:40 UTC, baykovr commented on trurl.c
> +      op->accept_space = false;
Fixed

2023-04-07 20:40 UTC, baykovr commented on trurl.c
> +  "unsupported CURLUcode error"
Fixed

2023-04-07 22:07 UTC, bagder commented on trurl.c
> +  fprintf(stderr, "URL error: %s\n", curl_easy_strerror(error))
Ah right, you would have to provide a fake version of `curl_url_strerror()` that returns the proper string. Like:
~~~c
static char *fake_strerror(CURLUcode error)
{
  static buffer[128];
  curl_msnprintf(buffer, sizeof(buffer), "CURLUcode: %d\n", error);
  return buffer;
}

2023-04-08 21:01 UTC, bagder commented
@baykovr please take a new look at how master runs for you and see if most issues are not already fixed

2023-04-10 08:45 UTC, bagder commented
I believe this is already addressed. If there are remaining issues, please let us know!

2023-04-10 08:45 UTC, closed without merging

2023-04-10 16:59 UTC, baykovr commented
> @baykovr please take a new look at how master runs for you and see if most issues are not already fixed

Works well, thanks.